In [13]:
import pandas as pd
import numpy as np
from Bio import SeqIO
from Bio.SeqRecord import SeqRecord
import edlib

In [14]:
colors = []
sequences = []
for record in SeqIO.parse('seq1000_1.fa', 'fasta'):
    colors.append(int(record.id.split('_')[1][3:]))
    sequences.append(str(record.seq))
#print(colors)
print(np.unique(colors))

[ 1  5 19]


In [15]:
dist_matrix = np.zeros((len(sequences), len(sequences)), dtype='int')
for i in range(len(sequences)):
    for j in range(i, len(sequences)):
        dist_matrix[i, j] = edlib.align(sequences[i], sequences[j], mode='HW', task='path')['editDistance']
dist_matrix = dist_matrix + dist_matrix.T
print(dist_matrix)

[[ 0 15 42 ... 48 42 43]
 [15  0 50 ... 56 51 51]
 [42 50  0 ... 19  2  1]
 ...
 [48 56 19 ...  0 22 21]
 [42 51  2 ... 22  0  3]
 [43 51  1 ... 21  3  0]]


In [16]:
edges = np.zeros((len(sequences), len(sequences)), dtype='float')
count = 0
for i in range(len(sequences)):
    for j in range(i, len(sequences)):
        if 0 < dist_matrix[i, j] < 10:
            edges[i, j] = dist_matrix[i, j]
            count += 1
print(count)

79860


In [17]:
def chromosome_to_color(chromosome):
    if chromosome == 1:
        return 'blue'
    elif chromosome == 5:
        return 'green'
    elif chromosome == 16:
        return 'yellow'
    else:
        return 'red'

In [18]:
f = open('graph_seq1000_1_chr.graphml', 'w')
f.write('<?xml version="1.0" encoding="UTF-8"?>\n')
f.write('<graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n')
f.write('xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">\n')
f.write('<key id="d0" for="node" attr.name="color" attr.type="string">\n')
f.write('<default>yellow</default>\n')
f.write('</key>\n')
f.write('<key id="d1" for="edge" attr.name="weight" attr.type="double"/>\n')
f.write('<graph id="G" edgedefault="undirected">\n')
for i in range(len(colors)):
    f.write(f'<node id="n{i}">\n')
    f.write(f'<data key="d0">{chromosome_to_color(colors[i])}</data>\n')
    f.write('</node>\n')
count = 0
for i in range(len(sequences)):
    for j in range(i + 1, len(sequences)):
        if edges[i, j] > 0:
            f.write(f'<edge id="e{count}" source="n{i}" target="n{j}">\n')
            f.write(f'<data key="d1">{edges[i, j]}</data>\n')
            f.write(f'</edge>')
            count += 1
#<edge id="e3" source="n3" target="n2"/>
#<edge id="e4" source="n2" target="n4"/>
#<edge id="e5" source="n3" target="n5"/>
#<edge id="e6" source="n5" target="n4">
f.write('</graph>\n')
f.write('</graphml>')
f.close()

In [19]:
colors = []
sequences = []
for record in SeqIO.parse('seq2000_1.fa', 'fasta'):
    colors.append(int(record.id.split('_')[1][3:]))
    sequences.append(str(record.seq))
#print(colors)
print(np.unique(colors))

[ 1  5 19]


In [20]:
dist_matrix = np.zeros((len(sequences), len(sequences)), dtype='int')
for i in range(len(sequences)):
    for j in range(i, len(sequences)):
        dist_matrix[i, j] = edlib.align(sequences[i], sequences[j], mode='HW', task='path')['editDistance']
dist_matrix = dist_matrix + dist_matrix.T
print(dist_matrix)

[[ 0 45 15 ... 79  8 79]
 [45  0 52 ... 81 49 82]
 [15 52  0 ... 85 17 83]
 ...
 [79 81 85 ...  0 84 44]
 [ 8 49 17 ... 84  0 81]
 [79 82 83 ... 44 81  0]]


In [21]:
edges = np.zeros((len(sequences), len(sequences)), dtype='float')
count = 0
for i in range(len(sequences)):
    for j in range(i, len(sequences)):
        if 0 < dist_matrix[i, j] < 10:
            edges[i, j] = dist_matrix[i, j]
            count += 1
print(count)

288689


In [22]:
f = open('graph_seq2000_1_chr.graphml', 'w')
f.write('<?xml version="1.0" encoding="UTF-8"?>\n')
f.write('<graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n')
f.write('xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">\n')
f.write('<key id="d0" for="node" attr.name="color" attr.type="string">\n')
f.write('<default>yellow</default>\n')
f.write('</key>\n')
f.write('<key id="d1" for="edge" attr.name="weight" attr.type="double"/>\n')
f.write('<graph id="G" edgedefault="undirected">\n')
for i in range(len(colors)):
    f.write(f'<node id="n{i}">\n')
    f.write(f'<data key="d0">{chromosome_to_color(colors[i])}</data>\n')
    f.write('</node>\n')
count = 0
for i in range(len(sequences)):
    for j in range(i + 1, len(sequences)):
        if edges[i, j] > 0:
            f.write(f'<edge id="e{count}" source="n{i}" target="n{j}">\n')
            f.write(f'<data key="d1">{edges[i, j]}</data>\n')
            f.write(f'</edge>')
            count += 1
#<edge id="e3" source="n3" target="n2"/>
#<edge id="e4" source="n2" target="n4"/>
#<edge id="e5" source="n3" target="n5"/>
#<edge id="e6" source="n5" target="n4">
f.write('</graph>\n')
f.write('</graphml>')
f.close()

In [23]:
colors = []
sequences = []
for record in SeqIO.parse('seq2000_2.fa', 'fasta'):
    colors.append(int(record.id.split('_')[1][3:]))
    sequences.append(str(record.seq))
#print(colors)
print(np.unique(colors))

[ 1  5 19]


In [24]:
dist_matrix = np.zeros((len(sequences), len(sequences)), dtype='float')
for i in range(len(sequences)):
    for j in range(i, len(sequences)):
        dist_matrix[i, j] = edlib.align(sequences[i], sequences[j], mode='HW', task='path')['editDistance']
dist_matrix = dist_matrix + dist_matrix.T
print(dist_matrix)

[[ 0. 80. 25. ... 53. 16. 80.]
 [80.  0. 83. ... 81. 85. 10.]
 [25. 83.  0. ... 56. 18. 82.]
 ...
 [53. 81. 56. ...  0. 48. 82.]
 [16. 85. 18. ... 48.  0. 84.]
 [80. 10. 82. ... 82. 84.  0.]]


In [25]:
edges = np.zeros((len(sequences), len(sequences)), dtype='float')
count = 0
for i in range(len(sequences)):
    for j in range(i, len(sequences)):
        if 0 < dist_matrix[i, j] < 10:
            edges[i, j] = dist_matrix[i, j]
            count += 1
print(count)

263097


In [26]:
f = open('graph_seq2000_2_chr.graphml', 'w')
f.write('<?xml version="1.0" encoding="UTF-8"?>\n')
f.write('<graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n')
f.write('xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">\n')
f.write('<key id="d0" for="node" attr.name="color" attr.type="string">\n')
f.write('<default>yellow</default>\n')
f.write('</key>\n')
f.write('<key id="d1" for="edge" attr.name="weight" attr.type="double"/>\n')
f.write('<graph id="G" edgedefault="undirected">\n')
for i in range(len(colors)):
    f.write(f'<node id="n{i}">\n')
    f.write(f'<data key="d0">{chromosome_to_color(colors[i])}</data>\n')
    f.write('</node>\n')
count = 0
for i in range(len(sequences)):
    for j in range(i + 1, len(sequences)):
        if edges[i, j] > 0:
            f.write(f'<edge id="e{count}" source="n{i}" target="n{j}">\n')
            f.write(f'<data key="d1">{edges[i, j]}</data>\n')
            f.write(f'</edge>')
            count += 1
#<edge id="e3" source="n3" target="n2"/>
#<edge id="e4" source="n2" target="n4"/>
#<edge id="e5" source="n3" target="n5"/>
#<edge id="e6" source="n5" target="n4">
f.write('</graph>\n')
f.write('</graphml>')
f.close()

In [27]:
colors = []
sequences = []
for record in SeqIO.parse('seq2000_3.fa', 'fasta'):
    colors.append(int(record.id.split('_')[1][3:]))
    sequences.append(str(record.seq))
#print(colors)
print(np.unique(colors))

[ 1  5 19]


In [28]:
dist_matrix = np.zeros((len(sequences), len(sequences)), dtype='float')
for i in range(len(sequences)):
    for j in range(i, len(sequences)):
        dist_matrix[i, j] = edlib.align(sequences[i], sequences[j], mode='HW', task='path')['editDistance']
dist_matrix = dist_matrix + dist_matrix.T
print(dist_matrix)

[[ 0.  4. 43. ... 44. 20. 81.]
 [ 4.  0. 45. ... 46. 22. 82.]
 [43. 45.  0. ... 12. 53. 82.]
 ...
 [44. 46. 12. ...  0. 55. 80.]
 [20. 22. 53. ... 55.  0. 82.]
 [81. 82. 82. ... 80. 82.  0.]]


In [29]:
edges = np.zeros((len(sequences), len(sequences)), dtype='float')
count = 0
for i in range(len(sequences)):
    for j in range(i, len(sequences)):
        if 0 < dist_matrix[i, j] < 10:
            edges[i, j] = dist_matrix[i, j]
            count += 1
print(count)

295407


In [30]:
f = open('graph_seq2000_3_chr.graphml', 'w')
f.write('<?xml version="1.0" encoding="UTF-8"?>\n')
f.write('<graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n')
f.write('xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">\n')
f.write('<key id="d0" for="node" attr.name="color" attr.type="string">\n')
f.write('<default>yellow</default>\n')
f.write('</key>\n')
f.write('<key id="d1" for="edge" attr.name="weight" attr.type="double"/>\n')
f.write('<graph id="G" edgedefault="undirected">\n')
for i in range(len(colors)):
    f.write(f'<node id="n{i}">\n')
    f.write(f'<data key="d0">{chromosome_to_color(colors[i])}</data>\n')
    f.write('</node>\n')
count = 0
for i in range(len(sequences)):
    for j in range(i + 1, len(sequences)):
        if edges[i, j] > 0:
            f.write(f'<edge id="e{count}" source="n{i}" target="n{j}">\n')
            f.write(f'<data key="d1">{edges[i, j]}</data>\n')
            f.write(f'</edge>')
            count += 1
#<edge id="e3" source="n3" target="n2"/>
#<edge id="e4" source="n2" target="n4"/>
#<edge id="e5" source="n3" target="n5"/>
#<edge id="e6" source="n5" target="n4">
f.write('</graph>\n')
f.write('</graphml>')
f.close()