In [25]:
import edlib
from Bio import SeqIO
from Bio.SeqRecord import SeqRecord
import numpy as np
import pandas as pd

In [7]:
sequences = []
for record in SeqIO.parse('/Users/olga/Downloads/sampled100.fa', 'fasta'):
    sequences.append(str(record.seq))
#print(sequences)

In [15]:
dist_matrix = np.zeros((len(sequences), len(sequences)), dtype='int')
for i in range(len(sequences)):
    for j in range(i, len(sequences)):
        dist_matrix[i, j] = edlib.align(sequences[i], sequences[j], mode='HW', task='path')['editDistance']
dist_matrix = dist_matrix + dist_matrix.T
print(dist_matrix)

[[ 0 18 14 ...  0 15 12]
 [18  0 21 ... 18 13 10]
 [14 21  0 ... 14 15 15]
 ...
 [ 0 18 14 ...  0 15 12]
 [15 13 15 ... 15  0  7]
 [12 10 15 ... 12  7  0]]


In [22]:
edges = np.zeros((len(sequences), len(sequences)), dtype='int')
count = 0
for i in range(len(sequences)):
    for j in range(i, len(sequences)):
        if 0 < dist_matrix[i, j] < 5:
            edges[i, j] = 1
            count += 1
print(count)

445


In [27]:
df = pd.DataFrame(data=edges)
df.to_csv('edges100.csv')

In [30]:
sequences = []
for record in SeqIO.parse('/Users/olga/Downloads/sampled1000.fa', 'fasta'):
    sequences.append(str(record.seq))
#print(sequences)

In [31]:
dist_matrix = np.zeros((len(sequences), len(sequences)), dtype='int')
for i in range(len(sequences)):
    for j in range(i, len(sequences)):
        dist_matrix[i, j] = edlib.align(sequences[i], sequences[j], mode='HW', task='path')['editDistance']
dist_matrix = dist_matrix + dist_matrix.T
print(dist_matrix)

[[0 8 7 ... 7 9 8]
 [8 0 7 ... 7 8 6]
 [7 7 0 ... 6 7 7]
 ...
 [7 7 6 ... 0 8 7]
 [9 8 7 ... 8 0 8]
 [8 6 7 ... 7 8 0]]


In [32]:
edges = np.zeros((len(sequences), len(sequences)), dtype='int')
count = 0
for i in range(len(sequences)):
    for j in range(i, len(sequences)):
        if 0 < dist_matrix[i, j] < 5:
            edges[i, j] = 1
            count += 1
print(count)

46725


In [33]:
df = pd.DataFrame(data=edges)
df.to_csv('edges1000.csv')

In [34]:
sequences = []
for record in SeqIO.parse('/Users/olga/Downloads/sampled1000.fa', 'fasta'):
    sequences.append(str(record.seq))
#print(sequences)

In [35]:
dist_matrix = np.zeros((len(sequences), len(sequences)), dtype='int')
for i in range(len(sequences)):
    for j in range(i, len(sequences)):
        dist_matrix[i, j] = edlib.align(sequences[i], sequences[j], mode='HW', task='path')['editDistance']
dist_matrix = dist_matrix + dist_matrix.T
print(dist_matrix)

[[0 8 7 ... 7 9 8]
 [8 0 7 ... 7 8 6]
 [7 7 0 ... 6 7 7]
 ...
 [7 7 6 ... 0 8 7]
 [9 8 7 ... 8 0 8]
 [8 6 7 ... 7 8 0]]


In [37]:
edges = np.zeros((len(sequences), len(sequences)), dtype='int')
count = 0
for i in range(len(sequences)):
    for j in range(i, len(sequences)):
        if dist_matrix[i, j] >= 5:
            edges[i, j] = 0
            count += 1
print(count)

448464


In [38]:
df = pd.DataFrame(data=edges)
df.to_csv('edges1000weighted.csv')